In [1]:
import numpy as np
import arepo
import matplotlib.pyplot as plt

In [2]:
basepath = '/n/holylfs05/LABS/hernquist_lab/Users/abeane/GSEgas/'

In [4]:
sn = arepo.Snapshot(basepath + 'runs/MWiso_fg0.5_Z0_star/lvl4/output-old2/', 10, combineFiles=True)
sn0 = arepo.Snapshot(basepath + 'runs/MWiso_fg0.5_Z0_star/lvl4/output/', 0, combineFiles=True)
ics = arepo.Snapshot(basepath + 'runs/MWiso_fg0.5_Z0_star/lvl4/ICs/ics.hdf5', combineFiles=True)

In [5]:
sn.Time

0.05029297 3.57139e+11 d

In [7]:
sn0.part4.GFM_Metals

array([[7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00],
       [7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00],
       [7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00],
       ...,
       [7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00],
       [7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00],
       [7.388e-01, 2.485e-01, 2.400e-03, ..., 7.000e-04, 1.300e-03,
        0.000e+00]], dtype=float32)

In [6]:
sn.part4.CumSNIINumber[sn.part4.GFM_StellarFormationTime==1e-15]

array([706., 712., 703., 683., 697., 729., 691., 704., 730., 713., 656.,
       735., 729., 752., 720., 683., 718., 706., 643., 709., 668., 713.,
       685., 745., 647., 662., 719., 738., 699., 735., 704., 728., 681.,
       671., 688., 721., 758., 758., 690., 747., 701., 717., 689., 715.,
       714., 723., 717., 730., 741., 702., 685., 694., 741., 755., 751.,
       704., 731., 748., 703., 686., 724., 697., 696., 741., 676., 705.,
       709., 741., 698., 695., 702., 694., 687., 724., 696., 707., 739.,
       691., 732., 718., 710., 745., 708., 690., 675., 797., 698., 660.,
       659., 719., 709., 761., 717., 713., 670., 661., 684., 685., 711.,
       744., 707., 695., 696., 713., 754., 729., 694., 714., 741., 666.,
       788., 694., 673., 631., 679., 705., 699., 700., 690., 697., 692.,
       742., 689., 766., 740., 680., 672., 726., 717., 706., 702., 712.,
       710., 688., 723., 666., 653., 724., 730., 699., 704., 705., 758.,
       737., 726., 719., 677., 696., 732., 683., 71

In [7]:
in_ics = sn.part4.GFM_StellarFormationTime==1e-15
np.unique(sn.part4.MassReleased[in_ics])

array([1.08359245e-10, 2.16733617e-10, 4.33527714e-10, 5.70936298e-10,
       8.67297734e-10, 1.00470632e-09], dtype=float32)

In [12]:
in_ics = sn.part4.GFM_StellarFormationTime>1e-15
print(len(np.where(in_ics)[0]))
np.unique(sn.part4.MassReleased[in_ics])

2375


array([0.00000000e+00, 7.48858822e-11, 1.06670610e-10, 1.08096906e-10,
       1.17325233e-10, 1.24322552e-10, 1.35201267e-10, 1.39248002e-10,
       1.46620868e-10, 1.68281458e-10, 1.74507339e-10, 1.76696213e-10,
       1.82711818e-10, 1.84971941e-10, 1.87389410e-10, 1.93372499e-10,
       2.04759751e-10, 2.08761411e-10, 2.37830811e-10, 2.47104781e-10,
       2.52063592e-10, 2.58763178e-10, 2.63732980e-10, 2.64420985e-10,
       2.70852701e-10, 2.76298096e-10, 2.77422224e-10, 2.81534657e-10,
       2.87536162e-10, 2.91090346e-10, 2.93485097e-10, 2.93926689e-10,
       2.97562863e-10, 3.08793158e-10, 3.10392406e-10, 3.25792560e-10,
       3.27699784e-10, 3.31177974e-10, 3.32200961e-10, 3.36939837e-10,
       3.41657092e-10, 3.42165490e-10, 3.43445189e-10, 3.50147300e-10,
       3.51267349e-10, 3.55393298e-10, 3.55976970e-10, 3.66948749e-10,
       3.68541558e-10, 3.71106729e-10, 3.72168019e-10, 3.73247849e-10,
       3.75205561e-10, 3.77244458e-10, 3.78245518e-10, 3.80686288e-10,
      

In [27]:
dir(sn.part4)

['Acceleration',
 'BirthDensity',
 'BirthPos',
 'BirthVel',
 'ColumnDensity',
 'Coordinates',
 'CumFeedbackMomentum',
 'CumInjFeedbackMomentum',
 'CumInjFeedbackMomentumAGB',
 'CumSNIINumber',
 'CumSNIaNumber',
 'Cum_RadMomentumRealInjected',
 'Cum_RadiationMomentumReleased',
 'FeedbackEnergy',
 'FeedbackMomentum',
 'FeedbackMomentumAGB',
 'GFM_InitialMass',
 'GFM_Metallicity',
 'GFM_Metals',
 'GFM_StellarFormationTime',
 'LocISMDens',
 'MassReleased',
 'Masses',
 'NormSphRadFeedback',
 'ParticleIDs',
 'Potential',
 'RadCoolShutoffTime',
 'RadFeedTau',
 'RadFeed_NumNgb',
 'RadiationMomentumReleased',
 'SNIINumber',
 'SNIaNumber',
 'Softenings',
 'StarsHsml',
 'StarsMaxRadius',
 'StromgrenRadius',
 'Velocities',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__'

In [48]:
sn.part4.Hsml[np.logical_not(in_ics)][:100]

AttributeError: unknown field 'Hsml' for particle group 4

In [28]:
dir(sn.part4)[:40]

['Acceleration',
 'BirthDensity',
 'BirthPos',
 'BirthVel',
 'ColumnDensity',
 'Coordinates',
 'CumFeedbackMomentum',
 'CumInjFeedbackMomentum',
 'CumInjFeedbackMomentumAGB',
 'CumSNIINumber',
 'CumSNIaNumber',
 'Cum_RadMomentumRealInjected',
 'Cum_RadiationMomentumReleased',
 'FeedbackEnergy',
 'FeedbackMomentum',
 'FeedbackMomentumAGB',
 'GFM_InitialMass',
 'GFM_Metallicity',
 'GFM_Metals',
 'GFM_StellarFormationTime',
 'LocISMDens',
 'MassReleased',
 'Masses',
 'NormSphRadFeedback',
 'ParticleIDs',
 'Potential',
 'RadCoolShutoffTime',
 'RadFeedTau',
 'RadFeed_NumNgb',
 'RadiationMomentumReleased',
 'SNIINumber',
 'SNIaNumber',
 'Softenings',
 'StarsHsml',
 'StarsMaxRadius',
 'StromgrenRadius',
 'Velocities',
 '__class__',
 '__contains__',
 '__delattr__']