In [1]:
import numpy as np
import h5py as h5
import arepo

In [15]:
import illustris_python as il
TNGbase = '/n/holylfs05/LABS/hernquist_lab/IllustrisTNG/Runs/L35n2160TNG/output/'

In [2]:
t = h5.File('subhalo523889/props_subhalo523889snap099.h5', mode='r')

In [3]:
t.keys()

<KeysViewHDF5 ['Coordinates', 'Header', 'Masses', 'PartType', 'ParticleIDs', 'TracerID']>

In [9]:
for key in t.keys():
    if key != 'Header':
        print(key, t[key][10])

Coordinates [32356.60091437 34675.76256833  8216.57509915]
Masses 6.219737770152278e-06
PartType 4
ParticleIDs 140998113069
TracerID 100000013334


In [16]:
snap = il.snapshot.loadSubhalo(TNGbase, 99, 523889, 4)

In [19]:
key = np.where(snap['ParticleIDs'] == t['ParticleIDs'][10])[0][0]

In [21]:
print(snap['Coordinates'][key])

[32356.60091437 34675.76256833  8216.57509915]


In [24]:
# t0 = np.load('subhalo523889/tracers_subhalo523889.npy')
t0 = h5.File('subhalo523889/tracers_subhalo523889.h5', mode='r')

In [25]:
t0['TracerID'][:]

array([100000000790, 100000002070, 100000003350, ..., 110048118806,
       110048158486, 110048488982], dtype=uint64)

In [28]:
t0['ParentID'][:][t0['TracerID'][:] == 100000013334]

array([140998113069], dtype=uint64)

In [30]:
f = 'lvl4'
f[:4]

'lvl4'

In [31]:
np.argwhere(np.isin(snap['ParticleIDs'], t0['TracerID'][:])).ravel()

array([155855, 228098, 490440, 594956, 599809, 865842, 897557, 913150])

In [33]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
f = h5.File('subhalo523889/props_subhalo523889_snap000.h5', mode='r')
list(f.keys())

['Coordinates', 'Header', 'Masses', 'PartType', 'ParticleIDs', 'TracerID']

In [35]:
f['Header'].attrs.keys()

<KeysViewHDF5 ['Redshift', 'ScaleFactor', 'Time', 'TimeLookBack']>

In [38]:
def run(subID):
    name = 'subhalo' + str(subID)
    sub_dir = name
    
    # load in the tracer ids previously selected
    snap_list = np.arange(90, 100)
    files = []
    for i in snap_list:
        f = h5.File(sub_dir + '/props_' + name + '_snap' + str(i).zfill(3) + '.h5', 'r')
        files.append(f)
    
    keys = list(files[0].keys())
    out = {}
    for key in keys:
        out[key] = []
    
    header_keys = list(files[0]['Header'].attrs.keys())
    header_out = {}
    for hkey in header_keys:
        header_out[hkey] = []
    
    for f in files:
        for key in keys:
            if key == 'Header':
                for hkey in header_keys:
                    header_out[hkey].append(f['Header'].attrs[hkey])
            else:
                out[key].append(f[key][:])
    
    for key in keys:
        out[key] = np.array(out[key])
    
    for hkey in header_keys:
        header_out[hkey] = np.array(header_out[hkey])
    
    for f in files:
        f.close()
    
    return out, header_out

In [39]:
out, hout = run(523889)

In [42]:
out['Coordinates'][:,100,:]

array([[32560.45703125, 34802.54296875,  8306.58496094],
       [32543.39457868, 34793.05637821,  8298.57403612],
       [32515.29882812, 34777.23046875,  8287.06542969],
       [32493.38476562, 34764.79296875,  8279.86914062],
       [32465.34570312, 34745.80078125,  8264.86523438],
       [32448.140625  , 34737.3828125 ,  8258.70605469],
       [32419.26953125, 34718.6328125 ,  8246.04492188],
       [32397.49609375, 34704.4140625 ,  8238.27929688],
       [32371.81835938, 34685.69140625,  8224.64746094],
       [32351.52724786, 34675.92587471,  8220.37492641]])

In [44]:
hout['Time']

array([12.33638091, 12.46636533, 12.66263363, 12.79432756, 12.99311902,
       13.12646739, 13.3276986 , 13.46264534, 13.66623164, 13.80271999])

In [45]:
t = h5.File('subhalo523889/props_subhalo523889.h5', mode='r')

In [47]:
t['Coordinates'][99]

array([[32353.53348039, 34674.00017622,  8216.90853915],
       [32355.64691003, 34674.65275358,  8215.43834684],
       [32349.69406331, 34673.3874584 ,  8219.15757791],
       ...,
       [32349.35416927, 34669.78207036,  8214.8654687 ],
       [32350.55061638, 34676.53690213,  8222.15770971],
       [32350.08034483, 34675.68087366,  8221.32710052]])